"""Change user model

Revision ID: 8f6e5fd1d8d4
Revises: 07b2482bf9d3
Create Date: 2025-07-18 16:02:22.211530

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f6e5fd1d8d4"
down_revision: Union[str, Sequence[str], None] = "07b2482bf9d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_index(op.f("ix_user_model_email"), table_name="user_model")
    op.drop_column("user_model", "id")
    op.drop_column("user_model", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model", sa.Column("hashed_password", sa.VARCHAR(), nullable=False)
    )
    op.add_column("user_model", sa.Column("id", sa.INTEGER(), nullable=False))
    op.create_index(op.f("ix_user_model_email"), "user_model", ["email"], unique=1)
    op.drop_column("user_model", "password")
    # ### end Alembic commands ###
